// ignore_for_file: unnecessary_final

part of '../bindings_generator.dart';

/// Renders extracted Zig API metadata as Dart FFI declarations.
final class DartBindingEmitter {
  /// Creates an emitter for [api] with the specified native asset identifier.
  new({required this.api, required this.assetId}) : _opaqueTypes = {};

  /// The Zig declarations to render.
  final ZigApiDescription api;

  /// The native asset identifier embedded in generated bindings.
  final String assetId;
  final Set<String> _opaqueTypes;
  final Map<String, CallbackTypedefDecl> _callbackTypedefs =
      <String, CallbackTypedefDecl>{};

  /// Describes the public Dart functions rendered by this emitter.
  List<GeneratedDartFunction> describeFunctions() => [
    for (final function in api.functions)
      GeneratedDartFunction(
        name: _safeMemberIdentifier(function.name),
        returnType: _describeType(function.returnType),
        parameters: [
          for (final parameter in function.parameters)
            GeneratedDartParameter(
              name: _safeMemberIdentifier(parameter.name),
              type: _describeType(parameter.type),
            ),
        ],
      ),
  ];

  GeneratedDartType _describeType(ZigTypeRef type) => GeneratedDartType._(
    (prefix) => _dartType(type, namedTypePrefix: prefix),
    type is ZigPointerTypeRef,
  );

  /// Returns formatted Dart source for the configured API.
  ///
  /// Throws a [StateError] when a declaration cannot be represented by Dart
  /// FFI.
  String render() {
    final buffer = StringBuffer()
      ..writeln('// ignore_for_file: type=lint')
      ..writeln('// AUTO GENERATED FILE, DO NOT EDIT.')
      ..writeln('//')
      ..writeln('// Generated by `package:native_toolchain_zig`.');

    if (api.libraryComments.isNotEmpty) {
      _writeCommentBlock(buffer, api.libraryComments);
    }

    buffer
      ..writeln("@ffi.DefaultAsset('$assetId')")
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'dart:ffi' as ffi;")
      ..writeln();

    final reachableTypes = api.reachableTypes;
    _collectCallbackTypedefs(reachableTypes);

    for (final type in reachableTypes.where(
      (type) => type.kind == ZigContainerKind.enumType,
    )) {
      _writeEnum(buffer, type);
      buffer.writeln();
    }

    for (final callback in _callbackTypedefs.values) {
      _writeCallbackTypedef(buffer, callback);
      buffer.writeln();
    }

    for (final type in reachableTypes.where(
      (type) => type.kind != ZigContainerKind.enumType,
    )) {
      _writeCompoundType(buffer, type);
      buffer.writeln();
    }

    for (final global in api.globals) {
      _writeGlobal(buffer, global);
      buffer.writeln();
    }

    for (final function in api.functions) {
      _writeFunction(buffer, function);
      buffer.writeln();
    }

    for (final opaqueName in _opaqueTypes) {
      if (reachableTypes.any((t) => t.name == opaqueName)) {
        continue;
      }
      _writeOpaqueType(buffer, opaqueName);
      buffer.writeln();
    }

    return '${buffer.toString().trimRight()}\n';
  }

  /// Renders only the ABI types reachable from exported declarations.
  ///
  /// This library has no native asset reference or callable functions.
  String renderTypes() {
    final buffer = StringBuffer()
      ..writeln('// ignore_for_file: type=lint')
      ..writeln('// AUTO GENERATED FILE, DO NOT EDIT.')
      ..writeln('//')
      ..writeln('// ABI types generated by `package:native_toolchain_zig`.')
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'dart:ffi' as ffi;")
      ..writeln();

    final reachableTypes = api.reachableTypes;
    _collectCallbackTypedefs(reachableTypes);
    for (final type in reachableTypes.where(
      (type) => type.kind == ZigContainerKind.enumType,
    )) {
      _writeEnum(buffer, type);
      buffer.writeln();
    }
    for (final callback in _callbackTypedefs.values) {
      _writeCallbackTypedef(buffer, callback);
      buffer.writeln();
    }
    for (final type in reachableTypes.where(
      (type) => type.kind != ZigContainerKind.enumType,
    )) {
      _writeCompoundType(buffer, type);
      buffer.writeln();
    }
    for (final opaqueName in _opaqueTypes) {
      if (reachableTypes.any((type) => type.name == opaqueName)) {
        continue;
      }
      _writeOpaqueType(buffer, opaqueName);
      buffer.writeln();
    }
    return '${buffer.toString().trimRight()}\n';
  }

  void _writeEnum(StringBuffer buffer, ZigTypeDecl type) {
    if (type.tagType == null) {
      throw StateError('Enum ${type.name} must have an explicit tag type.');
    }

    _writeCommentBlock(buffer, type.comments);
    buffer.writeln('enum ${_safeTypeIdentifier(type.name)} {');
    for (var index = 0; index < type.enumCases.length; index++) {
      final enumCase = type.enumCases[index];
      final terminator = index == type.enumCases.length - 1 ? ';' : ',';
      _writeCommentBlock(buffer, enumCase.comments, indent: '  ');
      buffer.writeln(
        '  ${_safeValueIdentifier(enumCase.name)}(${enumCase.value})'
        '$terminator',
      );
    }
    buffer
      ..writeln()
      ..writeln('  const ${_safeTypeIdentifier(type.name)}(this.value);')
      ..writeln()
      ..writeln('  final int value;')
      ..writeln()
      ..writeln(
        '  static ${_safeTypeIdentifier(type.name)} fromValue(int value) => '
        'switch (value) {',
      );
    for (final enumCase in type.enumCases) {
      buffer.writeln(
        '    ${enumCase.value} => '
        '${_safeTypeIdentifier(type.name)}.'
        '${_safeValueIdentifier(enumCase.name)},',
      );
    }
    buffer
      ..writeln(
        '    _ => throw ArgumentError.value('
        "value, 'value', 'Unknown ${type.name} enum value'),",
      )
      ..writeln('  };')
      ..writeln('}');
  }

  void _writeOpaqueType(StringBuffer buffer, String name) {
    buffer.writeln(
      'final class ${_safeTypeIdentifier(name)} extends ffi.Opaque {}',
    );
  }

  void _writeCompoundType(StringBuffer buffer, ZigTypeDecl type) {
    if (type.layout == 'packed') {
      throw StateError(
        'Packed struct ${type.name} is unsupported: its backing-integer size, '
        'alignment, and calling convention cannot be preserved by Dart FFI.',
      );
    }

    if (!type.isExternContainer) {
      throw StateError(
        'Type ${type.name} must be declared as `extern ${switch (type.kind) {
          ZigContainerKind.structType => 'struct',
          ZigContainerKind.unionType => 'union',
          ZigContainerKind.enumType => 'enum',
        }}` to participate in the generated ABI surface.',
      );
    }

    _writeCommentBlock(buffer, type.comments);
    buffer.writeln(
      'final class ${_safeTypeIdentifier(type.name)} extends ffi.'
      '${switch (type.kind) {
        ZigContainerKind.structType => 'Struct',
        ZigContainerKind.unionType => 'Union',
        ZigContainerKind.enumType => throw StateError('Enums are emitted separately.'),
      }} {',
    );

    for (final member in type.members) {
      final memberType = member.type;
      if (memberType == null) {
        throw StateError(
          'Member ${member.name} in ${type.name} is missing a type annotation.',
        );
      }

      final safeName = _safeMemberIdentifier(member.name);
      if (_isDirectEnumType(memberType)) {
        final rawName = '${safeName}Raw';
        final annotation = _fieldAnnotation(_rawType(memberType));
        if (annotation != null) {
          buffer.writeln('  $annotation');
        }
        buffer
          ..writeln('  external ${_dartType(_rawType(memberType))} _$rawName;')
          ..writeln();
        _writeCommentBlock(buffer, member.comments, indent: '  ');
        buffer
          ..writeln(
            '  ${_dartType(memberType)} get $safeName => '
            '${_dartType(memberType)}.fromValue(_$rawName);',
          )
          ..writeln(
            '  set $safeName(${_dartType(memberType)} value) => '
            '_$rawName = value.value;',
          )
          ..writeln();
        continue;
      }

      _writeCommentBlock(buffer, member.comments, indent: '  ');
      final annotation = _fieldAnnotation(memberType);
      if (annotation != null) {
        buffer.writeln('  $annotation');
      }
      buffer
        ..writeln('  external ${_dartType(memberType)} $safeName;')
        ..writeln();
    }

    buffer.writeln('}');
  }

  void _writeGlobal(StringBuffer buffer, ZigGlobalDecl global) {
    final safeName = _safeMemberIdentifier(global.name);
    if (_isDirectEnumType(global.type)) {
      final rawName = '_${safeName}Raw';
      buffer
        ..writeln(
          '@ffi.Native<${_nativeType(_rawType(global.type))}>(symbol: '
          "'${global.name}')",
        )
        ..writeln('external ${_dartType(_rawType(global.type))} $rawName;')
        ..writeln();
      _writeCommentBlock(buffer, global.comments);
      buffer.writeln(
        '${_dartType(global.type)} get $safeName => '
        '${_dartType(global.type)}.fromValue($rawName);',
      );
      if (global.mutable) {
        buffer.writeln(
          'set $safeName(${_dartType(global.type)} value) => '
          '$rawName = value.value;',
        );
      }
      return;
    }

    _writeCommentBlock(buffer, global.comments);
    buffer
      ..writeln(
        '@ffi.Native<${_nativeType(global.type)}>(symbol: '
        "'${global.name}')",
      )
      ..writeln('external ${_dartType(global.type)} $safeName;');
  }

  void _writeFunction(StringBuffer buffer, ZigFunctionDecl function) {
    final safeName = _safeMemberIdentifier(function.name);
    final needsWrapper =
        _isDirectEnumType(function.returnType) ||
        function.parameters.any(
          (parameter) => _isDirectEnumType(parameter.type),
        );
    final renderedComments = _renderedFunctionComments(function);

    final externalName = needsWrapper ? '_${safeName}Raw' : safeName;
    if (!needsWrapper) {
      _writeCommentBlock(buffer, renderedComments);
    }
    buffer
      ..writeln(
        '@ffi.Native<${_nativeFunctionType(function)}>(symbol: '
        "'${function.name}')",
      )
      ..writeln(
        'external ${_dartType(_rawType(function.returnType))} $externalName('
        '${_rawParameterList(function)});',
      );

    if (!needsWrapper) {
      return;
    }

    final publicParameters = function.parameters
        .map(
          (parameter) =>
              '${_dartType(parameter.type)} '
              '${_safeMemberIdentifier(parameter.name)}',
        )
        .join(', ');
    final convertedArguments = function.parameters
        .map((parameter) {
          final safeParameterName = _safeMemberIdentifier(parameter.name);
          if (_isDirectEnumType(parameter.type)) {
            return '$safeParameterName.value';
          }
          return safeParameterName;
        })
        .join(', ');

    final publicReturnType = _dartType(function.returnType);
    if (publicReturnType == 'void') {
      buffer
        ..writeln()
        ..write(_commentBlockText(renderedComments))
        ..writeln('void $safeName($publicParameters) {')
        ..writeln('  $externalName($convertedArguments);')
        ..writeln('}');
      return;
    }

    if (_isDirectEnumType(function.returnType)) {
      buffer
        ..writeln()
        ..write(_commentBlockText(renderedComments))
        ..writeln('$publicReturnType $safeName($publicParameters) => ')
        ..writeln(
          '    $publicReturnType.fromValue($externalName($convertedArguments));',
        );
      return;
    }

    buffer
      ..writeln()
      ..write(_commentBlockText(renderedComments))
      ..writeln(
        '$publicReturnType $safeName($publicParameters) => '
        '$externalName($convertedArguments);',
      );
  }

  List<String> _renderedFunctionComments(ZigFunctionDecl function) {
    final comments = <String>[...function.comments];
    final documentedParameters = function.parameters
        .where((parameter) => parameter.comments.isNotEmpty)
        .toList();
    if (documentedParameters.isEmpty) {
      return comments;
    }

    if (comments.isNotEmpty) {
      comments.add('');
    }
    comments.add('Parameters:');
    for (final parameter in documentedParameters) {
      final safeName = _safeMemberIdentifier(parameter.name);
      final parameterComments = parameter.comments;
      comments.add('- `$safeName`: ${parameterComments.first}');
      for (final line in parameterComments.skip(1)) {
        comments.add(line.isEmpty ? '' : '  $line');
      }
    }

    return comments;
  }

  void _writeCommentBlock(
    StringBuffer buffer,
    List<String> comments, {
    String indent = '',
  }) {
    final block = _commentBlockText(comments, indent: indent);
    if (block.isNotEmpty) {
      buffer.write(block);
    }
  }

  String _commentBlockText(List<String> comments, {String indent = ''}) {
    if (comments.isEmpty) {
      return '';
    }

    final buffer = StringBuffer();
    for (final line in comments) {
      if (line.isEmpty) {
        buffer.writeln('$indent///');
      } else {
        buffer.writeln('$indent/// $line');
      }
    }
    return buffer.toString();
  }

  String _nativeFunctionType(ZigFunctionDecl function) {
    final nativeParameters = function.parameters
        .map((parameter) => _nativeType(_rawType(parameter.type)))
        .join(', ');
    return '${_nativeType(_rawType(function.returnType))} Function('
        '$nativeParameters)';
  }

  void _collectCallbackTypedefs(List<ZigTypeDecl> reachableTypes) {
    for (final type in reachableTypes) {
      for (final member in type.members) {
        final memberType = member.type;
        if (memberType != null) {
          _collectCallbackTypedefsFromType(
            memberType,
            contextName: type.name,
            memberName: member.name,
          );
        }
      }
    }

    for (final function in api.functions) {
      _collectCallbackTypedefsFromType(
        function.returnType,
        contextName: function.name,
        memberName: 'return',
      );
      for (final parameter in function.parameters) {
        _collectCallbackTypedefsFromType(
          parameter.type,
          contextName: function.name,
          memberName: parameter.name,
        );
      }
    }

    for (final global in api.globals) {
      _collectCallbackTypedefsFromType(
        global.type,
        contextName: global.name,
        memberName: 'value',
      );
    }
  }

  void _collectCallbackTypedefsFromType(
    ZigTypeRef type, {
    required String contextName,
    required String memberName,
  }) {
    switch (type) {
      case ZigPointerTypeRef(:final child):
        if (child case ZigFunctionTypeRef()) {
          _registerCallbackTypedef(
            contextName: contextName,
            memberName: memberName,
            functionType: child,
          );
        } else {
          _collectCallbackTypedefsFromType(
            child,
            contextName: contextName,
            memberName: memberName,
          );
        }
      case ZigArrayTypeRef(:final child):
        _collectCallbackTypedefsFromType(
          child,
          contextName: contextName,
          memberName: memberName,
        );
      case ZigFunctionTypeRef():
        _registerCallbackTypedef(
          contextName: contextName,
          memberName: memberName,
          functionType: type,
        );
      case ZigPrimitiveTypeRef():
        break;
      case ZigNamedTypeRef():
        break;
    }
  }

  void _registerCallbackTypedef({
    required String contextName,
    required String memberName,
    required ZigFunctionTypeRef functionType,
  }) {
    final baseName = _callbackTypedefBaseName(memberName);
    var typedefName = baseName;
    if (_callbackTypedefs.containsKey(typedefName) ||
        api.typeDeclForName(typedefName) != null) {
      typedefName = '${_safeTypeIdentifier(contextName)}$baseName';
    }
    var suffix = 2;
    while (_callbackTypedefs.containsKey(typedefName)) {
      typedefName = '${_safeTypeIdentifier(contextName)}$baseName$suffix';
      suffix += 1;
    }

    _callbackTypedefs.putIfAbsent(
      typedefName,
      () => CallbackTypedefDecl(name: typedefName, functionType: functionType),
    );
  }

  String _callbackTypedefBaseName(String memberName) {
    final pascal = _pascalCaseIdentifier(memberName);
    if (pascal.endsWith('Callback')) {
      return pascal;
    }
    return '${pascal}Callback';
  }

  String _pascalCaseIdentifier(String source) {
    final parts = source.split(RegExp('[^A-Za-z0-9]+'));
    final buffer = StringBuffer();

    for (final part in parts) {
      if (part.isEmpty) {
        continue;
      }
      buffer.write(part[0].toUpperCase());
      if (part.length > 1) {
        buffer.write(part.substring(1));
      }
    }

    return buffer.isEmpty ? 'Callback' : buffer.toString();
  }

  void _writeCallbackTypedef(
    StringBuffer buffer,
    CallbackTypedefDecl callback,
  ) {
    _writeCommentBlock(buffer, callback.comments);
    buffer.writeln(
      'typedef ${_safeTypeIdentifier(callback.name)} = '
      '${_nativeFunctionSignature(callback.functionType)};',
    );
  }

  String _rawParameterList(ZigFunctionDecl function) {
    return function.parameters
        .map(
          (parameter) =>
              '${_dartType(_rawType(parameter.type))} '
              '${_safeMemberIdentifier(parameter.name)}',
        )
        .join(', ');
  }

  ZigTypeRef _rawType(ZigTypeRef type) {
    if (type is ZigNamedTypeRef) {
      final decl = api.typeDeclForName(type.name);
      if (decl != null && decl.kind == ZigContainerKind.enumType) {
        final tagType = decl.tagType;
        if (tagType == null) {
          throw StateError('Enum ${decl.name} must have an explicit tag type.');
        }
        return tagType;
      }
    }
    return type;
  }

  bool _isDirectEnumType(ZigTypeRef type) {
    return switch (type) {
      ZigNamedTypeRef(:final name) =>
        api.typeDeclForName(name)?.kind == ZigContainerKind.enumType,
      _ => false,
    };
  }

  String _dartType(ZigTypeRef type, {String namedTypePrefix = ''}) {
    switch (type) {
      case ZigPrimitiveTypeRef(:final name):
        final spec = _primitiveSpecs[name];
        if (spec == null) {
          throw StateError('Unsupported Zig primitive type: $name');
        }
        return spec.dartType;
      case ZigNamedTypeRef(:final name):
        final decl = api.typeDeclForName(name);
        if (decl == null) {
          _opaqueTypes.add(name);
          return '$namedTypePrefix${_safeTypeIdentifier(name)}';
        }
        return '$namedTypePrefix${_safeTypeIdentifier(decl.name)}';
      case ZigPointerTypeRef(:final child):
        return 'ffi.Pointer<${_nativeType(_rawType(child), namedTypePrefix: namedTypePrefix)}>';
      case ZigArrayTypeRef(:final child):
        return 'ffi.Array<${_nativeType(child, namedTypePrefix: namedTypePrefix)}>';
      case ZigFunctionTypeRef():
        return 'ffi.NativeFunction<${_nativeFunctionSignature(type, namedTypePrefix: namedTypePrefix)}>';
    }
  }

  String _nativeType(ZigTypeRef type, {String namedTypePrefix = ''}) {
    switch (type) {
      case ZigPrimitiveTypeRef(:final name):
        final spec = _primitiveSpecs[name];
        if (spec == null) {
          throw StateError('Unsupported Zig primitive type: $name');
        }
        return spec.nativeType;
      case ZigNamedTypeRef(:final name):
        final decl = api.typeDeclForName(name);
        if (decl == null) {
          _opaqueTypes.add(name);
          return '$namedTypePrefix${_safeTypeIdentifier(name)}';
        }
        if (decl.kind == ZigContainerKind.enumType) {
          final tagType = decl.tagType;
          if (tagType == null) {
            throw StateError(
              'Enum ${decl.name} must have an explicit tag type.',
            );
          }
          return _nativeType(tagType, namedTypePrefix: namedTypePrefix);
        }
        return '$namedTypePrefix${_safeTypeIdentifier(decl.name)}';
      case ZigPointerTypeRef(:final child):
        return 'ffi.Pointer<${_nativeType(_rawType(child), namedTypePrefix: namedTypePrefix)}>';
      case ZigArrayTypeRef(:final child):
        return 'ffi.Array<${_nativeType(child, namedTypePrefix: namedTypePrefix)}>';
      case ZigFunctionTypeRef():
        return 'ffi.NativeFunction<${_nativeFunctionSignature(type, namedTypePrefix: namedTypePrefix)}>';
    }
  }

  String? _fieldAnnotation(ZigTypeRef type) {
    switch (type) {
      case ZigPrimitiveTypeRef(:final name):
        final spec = _primitiveSpecs[name];
        if (spec == null) {
          throw StateError('Unsupported Zig primitive type: $name');
        }
        return spec.fieldAnnotation;
      case ZigNamedTypeRef(:final name):
        final decl = api.typeDeclForName(name);
        if (decl == null) {
          throw StateError('Unsupported Zig named type: $name');
        }
        if (decl.kind == ZigContainerKind.enumType) {
          final tagType = decl.tagType;
          if (tagType == null) {
            throw StateError(
              'Enum ${decl.name} must have an explicit tag type.',
            );
          }
          return _fieldAnnotation(tagType);
        }
        return null;
      case ZigPointerTypeRef():
        return null;
      case ZigArrayTypeRef():
        final dimensions = _arrayDimensions(type);
        final dims = dimensions.join(', ');
        if (dimensions.length <= 5) {
          return '@ffi.Array($dims)';
        }
        return '@ffi.Array.multi([${dimensions.join(', ')}])';
      case ZigFunctionTypeRef():
        return null;
    }
  }

  List<int> _arrayDimensions(ZigTypeRef type) {
    final dimensions = <int>[];
    var current = type;

    while (true) {
      switch (current) {
        case ZigArrayTypeRef(:final count, :final sentinelSource, :final child):
          dimensions.add(count + (sentinelSource == null ? 0 : 1));
          current = child;
        default:
          return dimensions;
      }
    }
  }

  String _nativeFunctionSignature(
    ZigFunctionTypeRef type, {
    String namedTypePrefix = '',
  }) {
    final returnType = _nativeType(
      _rawType(type.returnType),
      namedTypePrefix: namedTypePrefix,
    );
    final parameters = type.parameters
        .map(
          (parameter) => _nativeType(
            _rawType(parameter),
            namedTypePrefix: namedTypePrefix,
          ),
        )
        .join(', ');
    return '$returnType Function($parameters)';
  }
}

/// A generated Dart typedef for a native callback signature.
final class CallbackTypedefDecl {
  /// Creates a callback typedef declaration.
  const new({required this.name, required this.functionType})
    : comments = const <String>[];

  /// The generated typedef name.
  final String name;

  /// The native callback signature.
  final ZigFunctionTypeRef functionType;

  /// Documentation comments emitted above the typedef.
  final List<String> comments;
}

const _dartKeywords = <String>{
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'base',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'of',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'sealed',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'when',
  'while',
  'with',
  'yield',
};

String _safeTypeIdentifier(String source) {
  final identifier = _sanitizeIdentifier(source);
  if (identifier.isEmpty) {
    throw StateError('Could not create a Dart type name from `$source`.');
  }
  return identifier;
}

String _safeMemberIdentifier(String source) {
  final identifier = _sanitizeIdentifier(source);
  if (identifier.isEmpty) {
    throw StateError('Could not create a Dart identifier from `$source`.');
  }
  return identifier;
}

String _safeValueIdentifier(String source) {
  final identifier = _sanitizeIdentifier(source);
  if (identifier.isEmpty) {
    throw StateError('Could not create a Dart enum value name from `$source`.');
  }
  return identifier;
}

String _sanitizeIdentifier(String source) {
  final replaced = source.replaceAll(RegExp('[^A-Za-z0-9_]'), '_');
  final prefixed = RegExp('^[0-9]').hasMatch(replaced)
      ? '_$replaced'
      : replaced;
  return _dartKeywords.contains(prefixed) ? '${prefixed}_' : prefixed;
}
