// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:dart_api/dart_api.dart')
library;

import 'dart:ffi' as ffi;

typedef Callback = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

typedef c_struct_unnamed_10Callback = ffi.Void Function(
  ffi.Pointer<ffi.Void>,
  ffi.Pointer<ffi.Void>,
);

final class c_struct_unnamed_5 extends ffi.Struct {
  @ffi.Int64()
  external int id;

  @ffi.Int64()
  external int origin_id;
}

final class c_struct_unnamed_6 extends ffi.Struct {
  @ffi.Int64()
  external int id;
}

final class c_struct_unnamed_7 extends ffi.Struct {
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Pointer<c_struct__Dart_CObject>> values;
}

final class c_struct_unnamed_8 extends ffi.Struct {
  @ffi.Uint32()
  external int type;

  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> values;
}

final class c_struct_unnamed_9 extends ffi.Struct {
  @ffi.Uint32()
  external int type;

  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> data;

  external ffi.Pointer<ffi.Void> peer;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >
  >
  callback;
}

final class c_struct_unnamed_10 extends ffi.Struct {
  @ffi.IntPtr()
  external int ptr;

  @ffi.IntPtr()
  external int size;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >
  >
  callback;
}

final class c_union_unnamed_4 extends ffi.Union {
  @ffi.Bool()
  external bool as_bool;

  @ffi.Int32()
  external int as_int32;

  @ffi.Int64()
  external int as_int64;

  @ffi.Double()
  external double as_double;

  external ffi.Pointer<ffi.Uint8> as_string;

  external c_struct_unnamed_5 as_send_port;

  external c_struct_unnamed_6 as_capability;

  external c_struct_unnamed_7 as_array;

  external c_struct_unnamed_8 as_typed_data;

  external c_struct_unnamed_9 as_external_typed_data;

  external c_struct_unnamed_10 as_native_pointer;
}

final class c_struct__Dart_CObject extends ffi.Struct {
  @ffi.Uint32()
  external int type;

  external c_union_unnamed_4 value;
}

final class Worker extends ffi.Struct {
  @ffi.Int64()
  external int receiver_port;

  @ffi.Int64()
  external int send_port;
}

@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>(symbol: 'dart_api_init')
external int dart_api_init(ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Pointer<Worker> Function(ffi.Int64)>(symbol: 'worker_create')
external ffi.Pointer<Worker> worker_create(int receiver_port);

@ffi.Native<ffi.Pointer<struct__Dart_Handle> Function(ffi.Pointer<Worker>)>(
  symbol: 'worker_get_send_port',
)
external ffi.Pointer<struct__Dart_Handle> worker_get_send_port(
  ffi.Pointer<Worker> worker,
);

@ffi.Native<
  ffi.Bool Function(ffi.Pointer<Worker>, ffi.Pointer<c_struct__Dart_CObject>)
>(symbol: 'worker_post')
external bool worker_post(
  ffi.Pointer<Worker> worker,
  ffi.Pointer<c_struct__Dart_CObject> obj,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<Worker>)>(symbol: 'worker_close')
external void worker_close(ffi.Pointer<Worker> worker);

final class struct__Dart_Handle extends ffi.Opaque {}
