// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:bindings/ffi.g.dart')
library;

import 'dart:ffi' as ffi;

final class Counter extends ffi.Struct {
  @ffi.Int64()
  external int value;

  @ffi.Int64()
  external int step;

}

@ffi.Native<ffi.Pointer<Counter> Function(ffi.Int64, ffi.Int64)>(symbol: 'counter_create')
external ffi.Pointer<Counter> counter_create(int initial, int step);

@ffi.Native<ffi.Void Function(ffi.Pointer<Counter>)>(symbol: 'counter_increment')
external void counter_increment(ffi.Pointer<Counter> counter);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<Counter>)>(symbol: 'counter_get')
external int counter_get(ffi.Pointer<Counter> counter);

@ffi.Native<ffi.Void Function(ffi.Pointer<Counter>)>(symbol: 'counter_destroy')
external void counter_destroy(ffi.Pointer<Counter> counter);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64)>(symbol: 'add')
external int add(int a, int b);

@ffi.Native<ffi.Double Function(ffi.Double, ffi.Double)>(symbol: 'multiply')
external double multiply(double a, double b);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Int64)>(symbol: 'clamp_value')
external int clamp_value(int value, int min_val, int max_val);
